### ISSUE TITLE
I need help with duplicated events on the day and time.

### ISSUE THREAD

**Issue by willmkt** [LaravelDaily/Laravel-FullCalendar-Recurring-Events#1]
First of all thanks for this project and the great tutorials!

I am currently working on a project similar to this one, and i'm stuck on how to make the validation for duplicated events.

On my case it is a clinic appointments, and i have many professionals and clients. I need to check before posting if the professional has a appointment on that date and time. 

On the same day and time can be many appointments for different professionals.

Can you guys help?? 

Thanks and keep up the good work!

**Comment by willmkt** [comment]
figured it out!

**Comment by SaundersB** [comment]
What did you do?
